#!/bin/sh

if [ $# -lt 2 ]; then
  echo "usage: draftzkmc <mc_name> <working_dir>"
  exit 1
fi

mc_name=$1
working_dir=$2

scriptdir=`dirname $0`

cp $scriptdir/resource/zkmctemplate $working_dir/zkmc.conf
echo mc_name=$mc_name >> $working_dir/zkmc.conf
