#!/bin/sh

if [ $# -lt 5 ]; then
  echo "usage: genmc <mc_name> <num_node> <num_crash> <strategy> <working_dir> [other_vars]"
  exit 1
fi

mc_name=$1
num_node=$2
num_crash=$3
strategy=$4
working_dir=$5
other_vars=$6

echo mc_name=$mc_name > $working_dir/mc.conf
echo working_dir=$working_dir >> $working_dir/mc.conf
echo traversal_record_dir=$working_dir/state >> $working_dir/mc.conf
echo test_record_dir=$working_dir/record >> $working_dir/mc.conf
echo exploring_strategy=$strategy >> $working_dir/mc.conf
echo num_node=$num_node >> $working_dir/mc.conf
echo num_crash=$num_crash >> $working_dir/mc.conf
for var in $other_vars; do
  echo $var >> $working_dir/mc.conf
done
